begin;

create table if not exists public.socios (
    id smallint primary key,
    nombre text not null,
    porcentaje numeric(5,2) not null default 50.00,
    activo boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint socios_id_check check (id in (1, 2)),
    constraint socios_nombre_check check (char_length(btrim(nombre)) between 1 and 80),
    constraint socios_porcentaje_check check (porcentaje = 50.00)
);

create table if not exists public.cortes_ganancias (
    id bigint generated by default as identity primary key,
    fecha date not null default current_date,
    caja_fisica_snapshot numeric not null check (caja_fisica_snapshot >= 0),
    retiros_efectivo_snapshot numeric not null check (retiros_efectivo_snapshot >= 0),
    caja_antes_socios_snapshot numeric not null check (caja_antes_socios_snapshot >= 0),
    deuda_tarjeta_snapshot numeric not null check (deuda_tarjeta_snapshot >= 0),
    base_repartible_snapshot numeric not null check (base_repartible_snapshot >= 0),
    cortes_previos_snapshot numeric not null check (cortes_previos_snapshot >= 0),
    maximo_nuevo_corte_snapshot numeric not null check (maximo_nuevo_corte_snapshot >= 0),
    monto_aprobado numeric not null check (
        monto_aprobado > 0
        and trunc(monto_aprobado) = monto_aprobado
        and mod(monto_aprobado, 2) = 0
    ),
    monto_socio_1 numeric not null check (monto_socio_1 >= 0),
    monto_socio_2 numeric not null check (monto_socio_2 >= 0),
    estado text not null default 'activo' check (estado in ('activo', 'anulado')),
    nota text not null default '',
    created_by uuid,
    created_at timestamptz not null default now(),
    anulado_at timestamptz,
    motivo_anulacion text,
    constraint cortes_ganancias_partes_check check (
        monto_socio_1 = monto_socio_2
        and monto_socio_1 + monto_socio_2 = monto_aprobado
    )
);

create table if not exists public.movimientos_socios (
    id bigint generated by default as identity primary key,
    corte_id bigint not null references public.cortes_ganancias(id),
    socio_id smallint not null references public.socios(id),
    tipo text not null check (tipo in ('retiro_efectivo', 'retiro_producto', 'reversion')),
    fecha date not null default current_date,
    valor_participacion_cop numeric not null,
    efecto_caja_cop numeric not null default 0,
    producto_id integer references public.productos(id),
    talla text,
    cantidad integer,
    costo_unitario_usd numeric,
    trm_snapshot numeric,
    costo_unitario_cop numeric,
    valor_comercial_unitario_cop numeric,
    revision_tributaria text not null default 'no_aplica'
        check (revision_tributaria in ('pendiente', 'revisado', 'no_aplica')),
    movimiento_revertido_id bigint references public.movimientos_socios(id),
    transaccion_origen_id bigint references public.transacciones(id),
    estado text not null default 'activo' check (estado in ('activo', 'revertido')),
    nota text not null default '',
    created_by uuid,
    created_at timestamptz not null default now(),
    constraint movimientos_socios_cantidad_check check (cantidad is null or cantidad > 0),
    constraint movimientos_socios_producto_check check (
        tipo <> 'retiro_producto'
        or (
            valor_participacion_cop > 0
            and efecto_caja_cop = 0
            and cantidad is not null
            and revision_tributaria in ('pendiente', 'revisado', 'no_aplica')
        )
    ),
    constraint movimientos_socios_efectivo_check check (
        tipo <> 'retiro_efectivo'
        or (
            valor_participacion_cop > 0
            and efecto_caja_cop = valor_participacion_cop
            and revision_tributaria = 'no_aplica'
        )
    ),
    constraint movimientos_socios_reversion_check check (
        tipo <> 'reversion'
        or (
            valor_participacion_cop < 0
            and movimiento_revertido_id is not null
            and revision_tributaria = 'no_aplica'
        )
    )
);

create unique index if not exists movimientos_socios_reversion_unica
    on public.movimientos_socios (movimiento_revertido_id)
    where movimiento_revertido_id is not null;

create unique index if not exists movimientos_socios_transaccion_origen_unica
    on public.movimientos_socios (transaccion_origen_id)
    where transaccion_origen_id is not null;

create index if not exists movimientos_socios_corte_idx
    on public.movimientos_socios (corte_id, fecha desc);

create index if not exists movimientos_socios_socio_idx
    on public.movimientos_socios (socio_id, fecha desc);

insert into public.socios (id, nombre, porcentaje, activo)
values
    (1, 'Socio 1', 50.00, true),
    (2, 'Socio 2', 50.00, true)
on conflict (id) do nothing;

alter table public.socios enable row level security;
alter table public.cortes_ganancias enable row level security;
alter table public.movimientos_socios enable row level security;

drop policy if exists "socios_authenticated_select" on public.socios;
create policy "socios_authenticated_select"
    on public.socios for select
    to authenticated
    using (true);

drop policy if exists "cortes_ganancias_authenticated_select" on public.cortes_ganancias;
create policy "cortes_ganancias_authenticated_select"
    on public.cortes_ganancias for select
    to authenticated
    using (true);

drop policy if exists "movimientos_socios_authenticated_select" on public.movimientos_socios;
create policy "movimientos_socios_authenticated_select"
    on public.movimientos_socios for select
    to authenticated
    using (true);

revoke all on table public.socios from anon;
revoke all on table public.cortes_ganancias from anon;
revoke all on table public.movimientos_socios from anon;
grant select on table public.socios to authenticated;
grant select on table public.cortes_ganancias to authenticated;
grant select on table public.movimientos_socios to authenticated;

create or replace function public.crear_corte_ganancias(
    p_monto_aprobado numeric,
    p_fecha date default current_date,
    p_nota text default ''
)
returns public.cortes_ganancias
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_caja_operativa numeric := 0;
    v_deuda numeric := 0;
    v_retiros_efectivo numeric := 0;
    v_caja_fisica numeric := 0;
    v_base numeric := 0;
    v_cortes_aprobados numeric := 0;
    v_disponible numeric := 0;
    v_row public.cortes_ganancias%rowtype;
begin
    if auth.uid() is null then
        raise exception 'Autenticacion requerida';
    end if;

    perform pg_advisory_xact_lock(hashtext('herencia90_socios_finanzas'));

    if p_monto_aprobado is null
       or p_monto_aprobado <= 0
       or trunc(p_monto_aprobado) <> p_monto_aprobado
       or mod(p_monto_aprobado, 2) <> 0 then
        raise exception 'El corte debe ser un valor COP positivo, entero y par';
    end if;

    select
        coalesce(sum(
            case
                when tipo = 'ingreso' then monto
                when tipo = 'gasto' and categoria <> 'Compra Inventario (con Tarjeta)' then -monto
                else 0
            end
        ), 0),
        greatest(0, coalesce(sum(
            case
                when tipo = 'gasto' and categoria = 'Compra Inventario (con Tarjeta)' then monto
                when tipo = 'gasto' and categoria = 'Pago Deuda Tarjeta/Socio' then -monto
                else 0
            end
        ), 0))
    into v_caja_operativa, v_deuda
    from public.transacciones;

    select coalesce(sum(efecto_caja_cop), 0)
    into v_retiros_efectivo
    from public.movimientos_socios;

    select coalesce(sum(monto_aprobado), 0)
    into v_cortes_aprobados
    from public.cortes_ganancias
    where estado = 'activo';

    v_caja_fisica := greatest(0, v_caja_operativa - v_retiros_efectivo);
    v_base := greatest(0, v_caja_fisica + v_retiros_efectivo - v_deuda);
    v_disponible := greatest(0, v_base - v_cortes_aprobados);

    if p_monto_aprobado > v_disponible then
        raise exception 'El corte supera el disponible actual de % COP', v_disponible;
    end if;

    insert into public.cortes_ganancias (
        fecha,
        caja_fisica_snapshot,
        retiros_efectivo_snapshot,
        caja_antes_socios_snapshot,
        deuda_tarjeta_snapshot,
        base_repartible_snapshot,
        cortes_previos_snapshot,
        maximo_nuevo_corte_snapshot,
        monto_aprobado,
        monto_socio_1,
        monto_socio_2,
        nota,
        created_by
    )
    values (
        coalesce(p_fecha, current_date),
        v_caja_fisica,
        greatest(0, v_retiros_efectivo),
        v_caja_fisica + v_retiros_efectivo,
        v_deuda,
        v_base,
        v_cortes_aprobados,
        v_disponible,
        p_monto_aprobado,
        p_monto_aprobado / 2,
        p_monto_aprobado / 2,
        coalesce(p_nota, ''),
        auth.uid()
    )
    returning * into v_row;

    return v_row;
end;
$$;

create or replace function public.registrar_retiro_efectivo_socio(
    p_corte_id bigint,
    p_socio_id smallint,
    p_monto numeric,
    p_fecha date default current_date,
    p_nota text default ''
)
returns public.movimientos_socios
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_asignado numeric := 0;
    v_usado numeric := 0;
    v_saldo numeric := 0;
    v_caja_operativa numeric := 0;
    v_retiros_efectivo numeric := 0;
    v_caja_fisica numeric := 0;
    v_row public.movimientos_socios%rowtype;
begin
    if auth.uid() is null then
        raise exception 'Autenticacion requerida';
    end if;

    perform pg_advisory_xact_lock(hashtext('herencia90_socios_finanzas'));

    if p_socio_id not in (1, 2) then
        raise exception 'Socio invalido';
    end if;

    if p_monto is null or p_monto <= 0 or trunc(p_monto) <> p_monto then
        raise exception 'El retiro debe ser un valor COP positivo y entero';
    end if;

    if not exists (
        select 1
        from public.cortes_ganancias
        where id = p_corte_id and estado = 'activo'
    ) then
        raise exception 'Corte inexistente o anulado';
    end if;

    select coalesce(sum(
        case when p_socio_id = 1 then monto_socio_1 else monto_socio_2 end
    ), 0)
    into v_asignado
    from public.cortes_ganancias
    where estado = 'activo';

    select coalesce(sum(valor_participacion_cop), 0)
    into v_usado
    from public.movimientos_socios
    where socio_id = p_socio_id;

    v_saldo := v_asignado - v_usado;
    if p_monto > v_saldo then
        raise exception 'Saldo insuficiente del socio. Disponible: % COP', v_saldo;
    end if;

    select coalesce(sum(
        case
            when tipo = 'ingreso' then monto
            when tipo = 'gasto' and categoria <> 'Compra Inventario (con Tarjeta)' then -monto
            else 0
        end
    ), 0)
    into v_caja_operativa
    from public.transacciones;

    select coalesce(sum(efecto_caja_cop), 0)
    into v_retiros_efectivo
    from public.movimientos_socios;

    v_caja_fisica := v_caja_operativa - v_retiros_efectivo;
    if p_monto > v_caja_fisica then
        raise exception 'Caja fisica insuficiente. Disponible: % COP', v_caja_fisica;
    end if;

    insert into public.movimientos_socios (
        corte_id,
        socio_id,
        tipo,
        fecha,
        valor_participacion_cop,
        efecto_caja_cop,
        revision_tributaria,
        nota,
        created_by
    )
    values (
        p_corte_id,
        p_socio_id,
        'retiro_efectivo',
        coalesce(p_fecha, current_date),
        p_monto,
        p_monto,
        'no_aplica',
        coalesce(p_nota, ''),
        auth.uid()
    )
    returning * into v_row;

    return v_row;
end;
$$;

create or replace function public.registrar_retiro_producto_socio(
    p_corte_id bigint,
    p_socio_id smallint,
    p_producto_id integer,
    p_talla text,
    p_cantidad integer,
    p_trm_snapshot numeric,
    p_fecha date default current_date,
    p_nota text default ''
)
returns public.movimientos_socios
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_product public.productos%rowtype;
    v_stock integer := 0;
    v_unit_cost_cop numeric := 0;
    v_total_cost_cop numeric := 0;
    v_asignado numeric := 0;
    v_usado numeric := 0;
    v_saldo numeric := 0;
    v_row public.movimientos_socios%rowtype;
begin
    if auth.uid() is null then
        raise exception 'Autenticacion requerida';
    end if;

    perform pg_advisory_xact_lock(hashtext('herencia90_socios_finanzas'));

    if p_socio_id not in (1, 2) then
        raise exception 'Socio invalido';
    end if;

    if p_cantidad is null or p_cantidad <= 0 then
        raise exception 'Cantidad invalida';
    end if;

    if p_talla is null or btrim(p_talla) = '' then
        raise exception 'Talla requerida';
    end if;

    if p_trm_snapshot is null or p_trm_snapshot <= 0 then
        raise exception 'TRM invalida';
    end if;

    if not exists (
        select 1
        from public.cortes_ganancias
        where id = p_corte_id and estado = 'activo'
    ) then
        raise exception 'Corte inexistente o anulado';
    end if;

    select *
    into v_product
    from public.productos
    where id = p_producto_id
    for update;

    if not found then
        raise exception 'Producto inexistente';
    end if;

    if coalesce(v_product.costo_usd, 0) <= 0 then
        raise exception 'El producto no tiene costo USD valido';
    end if;

    v_stock := coalesce((v_product.tallas ->> p_talla)::integer, 0);
    if p_cantidad > v_stock then
        raise exception 'Stock insuficiente. Disponible: %', v_stock;
    end if;

    v_unit_cost_cop := round(v_product.costo_usd * p_trm_snapshot);
    v_total_cost_cop := v_unit_cost_cop * p_cantidad;

    select coalesce(sum(
        case when p_socio_id = 1 then monto_socio_1 else monto_socio_2 end
    ), 0)
    into v_asignado
    from public.cortes_ganancias
    where estado = 'activo';

    select coalesce(sum(valor_participacion_cop), 0)
    into v_usado
    from public.movimientos_socios
    where socio_id = p_socio_id;

    v_saldo := v_asignado - v_usado;
    if v_total_cost_cop > v_saldo then
        raise exception 'Saldo insuficiente del socio. Disponible: % COP', v_saldo;
    end if;

    update public.productos
    set tallas = jsonb_set(
        coalesce(tallas, '{}'::jsonb),
        array[p_talla],
        to_jsonb(v_stock - p_cantidad),
        true
    )
    where id = p_producto_id;

    insert into public.movimientos_socios (
        corte_id,
        socio_id,
        tipo,
        fecha,
        valor_participacion_cop,
        efecto_caja_cop,
        producto_id,
        talla,
        cantidad,
        costo_unitario_usd,
        trm_snapshot,
        costo_unitario_cop,
        valor_comercial_unitario_cop,
        revision_tributaria,
        nota,
        created_by
    )
    values (
        p_corte_id,
        p_socio_id,
        'retiro_producto',
        coalesce(p_fecha, current_date),
        v_total_cost_cop,
        0,
        p_producto_id,
        p_talla,
        p_cantidad,
        v_product.costo_usd,
        p_trm_snapshot,
        v_unit_cost_cop,
        v_product.precio,
        'pendiente',
        coalesce(p_nota, ''),
        auth.uid()
    )
    returning * into v_row;

    return v_row;
end;
$$;

create or replace function public.revertir_movimiento_socio(
    p_movimiento_id bigint,
    p_fecha date default current_date,
    p_nota text default ''
)
returns public.movimientos_socios
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_original public.movimientos_socios%rowtype;
    v_product public.productos%rowtype;
    v_stock integer := 0;
    v_row public.movimientos_socios%rowtype;
begin
    if auth.uid() is null then
        raise exception 'Autenticacion requerida';
    end if;

    perform pg_advisory_xact_lock(hashtext('herencia90_socios_finanzas'));

    if p_nota is null or btrim(p_nota) = '' then
        raise exception 'Motivo de reversion requerido';
    end if;

    select *
    into v_original
    from public.movimientos_socios
    where id = p_movimiento_id
    for update;

    if not found then
        raise exception 'Movimiento inexistente';
    end if;

    if v_original.tipo = 'reversion' then
        raise exception 'Una reversion no puede revertirse';
    end if;

    if exists (
        select 1
        from public.movimientos_socios
        where movimiento_revertido_id = p_movimiento_id
    ) then
        raise exception 'El movimiento ya fue revertido';
    end if;

    if v_original.tipo = 'retiro_producto' and v_original.producto_id is not null then
        select *
        into v_product
        from public.productos
        where id = v_original.producto_id
        for update;

        if not found then
            raise exception 'No se puede restaurar el producto inexistente';
        end if;

        v_stock := coalesce((v_product.tallas ->> v_original.talla)::integer, 0);
        update public.productos
        set tallas = jsonb_set(
            coalesce(tallas, '{}'::jsonb),
            array[v_original.talla],
            to_jsonb(v_stock + v_original.cantidad),
            true
        )
        where id = v_original.producto_id;
    end if;

    insert into public.movimientos_socios (
        corte_id,
        socio_id,
        tipo,
        fecha,
        valor_participacion_cop,
        efecto_caja_cop,
        producto_id,
        talla,
        cantidad,
        costo_unitario_usd,
        trm_snapshot,
        costo_unitario_cop,
        valor_comercial_unitario_cop,
        revision_tributaria,
        movimiento_revertido_id,
        transaccion_origen_id,
        nota,
        created_by
    )
    values (
        v_original.corte_id,
        v_original.socio_id,
        'reversion',
        coalesce(p_fecha, current_date),
        -v_original.valor_participacion_cop,
        -v_original.efecto_caja_cop,
        v_original.producto_id,
        v_original.talla,
        v_original.cantidad,
        v_original.costo_unitario_usd,
        v_original.trm_snapshot,
        v_original.costo_unitario_cop,
        v_original.valor_comercial_unitario_cop,
        'no_aplica',
        v_original.id,
        null,
        btrim(p_nota),
        auth.uid()
    )
    returning * into v_row;

    update public.movimientos_socios
    set estado = 'revertido'
    where id = v_original.id;

    return v_row;
end;
$$;

create or replace function public.anular_corte_ganancias(
    p_corte_id bigint,
    p_motivo text
)
returns public.cortes_ganancias
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_corte public.cortes_ganancias%rowtype;
    v_saldo_movimientos numeric := 0;
begin
    if auth.uid() is null then
        raise exception 'Autenticacion requerida';
    end if;

    perform pg_advisory_xact_lock(hashtext('herencia90_socios_finanzas'));

    if p_motivo is null or char_length(btrim(p_motivo)) < 3 then
        raise exception 'Indica un motivo de anulacion';
    end if;

    select *
    into v_corte
    from public.cortes_ganancias
    where id = p_corte_id
    for update;

    if not found then
        raise exception 'Corte no encontrado';
    end if;

    if v_corte.estado <> 'activo' then
        raise exception 'El corte ya esta anulado';
    end if;

    select coalesce(sum(valor_participacion_cop), 0)
    into v_saldo_movimientos
    from public.movimientos_socios
    where corte_id = p_corte_id;

    if v_saldo_movimientos <> 0 then
        raise exception 'Revierte primero todos los retiros asociados al corte';
    end if;

    update public.cortes_ganancias
    set
        estado = 'anulado',
        anulado_at = now(),
        motivo_anulacion = btrim(p_motivo)
    where id = p_corte_id
    returning * into v_corte;

    return v_corte;
end;
$$;

create or replace function public.vincular_retiro_producto_historico(
    p_transaccion_id bigint,
    p_corte_id bigint,
    p_socio_id smallint,
    p_valor_participacion_cop numeric,
    p_nota text default ''
)
returns public.movimientos_socios
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_transaction public.transacciones%rowtype;
    v_asignado numeric := 0;
    v_usado numeric := 0;
    v_saldo numeric := 0;
    v_row public.movimientos_socios%rowtype;
begin
    if auth.uid() is null then
        raise exception 'Autenticacion requerida';
    end if;

    perform pg_advisory_xact_lock(hashtext('herencia90_socios_finanzas'));

    if p_socio_id not in (1, 2) then
        raise exception 'Socio invalido';
    end if;

    if p_valor_participacion_cop is null or p_valor_participacion_cop <= 0 then
        raise exception 'Valor historico invalido';
    end if;

    if not exists (
        select 1
        from public.cortes_ganancias
        where id = p_corte_id and estado = 'activo'
    ) then
        raise exception 'Corte inexistente o anulado';
    end if;

    select *
    into v_transaction
    from public.transacciones
    where id = p_transaccion_id;

    if not found or lower(coalesce(v_transaction.categoria, '')) not like '%retiro personal%' then
        raise exception 'La transaccion no es un retiro personal historico';
    end if;

    if exists (
        select 1 from public.movimientos_socios
        where transaccion_origen_id = p_transaccion_id
    ) then
        raise exception 'La transaccion historica ya fue vinculada';
    end if;

    select coalesce(sum(
        case when p_socio_id = 1 then monto_socio_1 else monto_socio_2 end
    ), 0)
    into v_asignado
    from public.cortes_ganancias
    where estado = 'activo';

    select coalesce(sum(valor_participacion_cop), 0)
    into v_usado
    from public.movimientos_socios
    where socio_id = p_socio_id;

    v_saldo := v_asignado - v_usado;
    if p_valor_participacion_cop > v_saldo then
        raise exception 'Saldo insuficiente del socio. Disponible: % COP', v_saldo;
    end if;

    insert into public.movimientos_socios (
        corte_id,
        socio_id,
        tipo,
        fecha,
        valor_participacion_cop,
        efecto_caja_cop,
        cantidad,
        costo_unitario_usd,
        trm_snapshot,
        costo_unitario_cop,
        revision_tributaria,
        transaccion_origen_id,
        nota,
        created_by
    )
    values (
        p_corte_id,
        p_socio_id,
        'retiro_producto',
        v_transaction.fecha,
        p_valor_participacion_cop,
        0,
        1,
        v_transaction.costo_usd_asociado,
        v_transaction.trm,
        p_valor_participacion_cop,
        'pendiente',
        p_transaccion_id,
        coalesce(nullif(btrim(p_nota), ''), v_transaction.descripcion, 'Retiro historico vinculado'),
        auth.uid()
    )
    returning * into v_row;

    return v_row;
end;
$$;

create or replace function public.actualizar_nombre_socio(
    p_socio_id smallint,
    p_nombre text
)
returns public.socios
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_row public.socios%rowtype;
begin
    if auth.uid() is null then
        raise exception 'Autenticacion requerida';
    end if;

    if p_socio_id not in (1, 2) then
        raise exception 'Socio invalido';
    end if;

    if p_nombre is null or char_length(btrim(p_nombre)) not between 1 and 80 then
        raise exception 'Nombre de socio invalido';
    end if;

    update public.socios
    set nombre = btrim(p_nombre),
        updated_at = now()
    where id = p_socio_id
    returning * into v_row;

    if not found then
        raise exception 'Socio inexistente';
    end if;

    return v_row;
end;
$$;

create or replace function public.actualizar_revision_tributaria_movimiento(
    p_movimiento_id bigint,
    p_estado text
)
returns public.movimientos_socios
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_row public.movimientos_socios%rowtype;
begin
    if auth.uid() is null then
        raise exception 'Autenticacion requerida';
    end if;

    if p_estado not in ('pendiente', 'revisado', 'no_aplica') then
        raise exception 'Estado tributario invalido';
    end if;

    update public.movimientos_socios
    set revision_tributaria = p_estado
    where id = p_movimiento_id
      and tipo = 'retiro_producto'
      and estado = 'activo'
    returning * into v_row;

    if not found then
        raise exception 'Solo se actualizan retiros de producto activos';
    end if;

    return v_row;
end;
$$;

revoke all on function public.crear_corte_ganancias(numeric, date, text) from public, anon;
grant execute on function public.crear_corte_ganancias(numeric, date, text) to authenticated;

revoke all on function public.registrar_retiro_efectivo_socio(bigint, smallint, numeric, date, text) from public, anon;
grant execute on function public.registrar_retiro_efectivo_socio(bigint, smallint, numeric, date, text) to authenticated;

revoke all on function public.registrar_retiro_producto_socio(bigint, smallint, integer, text, integer, numeric, date, text) from public, anon;
grant execute on function public.registrar_retiro_producto_socio(bigint, smallint, integer, text, integer, numeric, date, text) to authenticated;

revoke all on function public.revertir_movimiento_socio(bigint, date, text) from public, anon;
grant execute on function public.revertir_movimiento_socio(bigint, date, text) to authenticated;

revoke all on function public.anular_corte_ganancias(bigint, text) from public, anon;
grant execute on function public.anular_corte_ganancias(bigint, text) to authenticated;

revoke all on function public.vincular_retiro_producto_historico(bigint, bigint, smallint, numeric, text) from public, anon;
grant execute on function public.vincular_retiro_producto_historico(bigint, bigint, smallint, numeric, text) to authenticated;

revoke all on function public.actualizar_nombre_socio(smallint, text) from public, anon;
grant execute on function public.actualizar_nombre_socio(smallint, text) to authenticated;

revoke all on function public.actualizar_revision_tributaria_movimiento(bigint, text) from public, anon;
grant execute on function public.actualizar_revision_tributaria_movimiento(bigint, text) to authenticated;

commit;
