begin;

create table if not exists public.inventario_auditorias (
    id uuid primary key default gen_random_uuid(),
    owner_id uuid not null default auth.uid(),
    estado text not null default 'activa' check (estado in ('activa', 'completada')),
    total_referencias integer not null default 0 check (total_referencias >= 0),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    completed_at timestamptz
);

create table if not exists public.inventario_auditoria_items (
    id bigint generated by default as identity primary key,
    audit_id uuid not null references public.inventario_auditorias(id) on delete cascade,
    product_id integer not null,
    equipo text not null,
    descripcion text not null default '',
    imagen text not null default '',
    expected_counts jsonb not null default '{}'::jsonb,
    physical_counts jsonb not null default '{}'::jsonb,
    issue text not null default '' check (issue in ('', 'no_aparece', 'talla_diferente', 'defectuosa', 'otra')),
    note text not null default '',
    reviewed boolean not null default false,
    reviewed_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (audit_id, product_id)
);

create index if not exists inventario_auditorias_owner_estado_idx
    on public.inventario_auditorias (owner_id, estado, updated_at desc);

create index if not exists inventario_auditoria_items_audit_idx
    on public.inventario_auditoria_items (audit_id, reviewed, product_id);

alter table public.inventario_auditorias enable row level security;
alter table public.inventario_auditoria_items enable row level security;

drop policy if exists "inventario_auditorias_owner_select" on public.inventario_auditorias;
create policy "inventario_auditorias_owner_select"
    on public.inventario_auditorias for select
    to authenticated
    using (owner_id = auth.uid());

drop policy if exists "inventario_auditorias_owner_insert" on public.inventario_auditorias;
create policy "inventario_auditorias_owner_insert"
    on public.inventario_auditorias for insert
    to authenticated
    with check (owner_id = auth.uid());

drop policy if exists "inventario_auditorias_owner_update" on public.inventario_auditorias;
create policy "inventario_auditorias_owner_update"
    on public.inventario_auditorias for update
    to authenticated
    using (owner_id = auth.uid())
    with check (owner_id = auth.uid());

drop policy if exists "inventario_auditorias_owner_delete" on public.inventario_auditorias;
create policy "inventario_auditorias_owner_delete"
    on public.inventario_auditorias for delete
    to authenticated
    using (owner_id = auth.uid());

drop policy if exists "inventario_auditoria_items_owner_select" on public.inventario_auditoria_items;
create policy "inventario_auditoria_items_owner_select"
    on public.inventario_auditoria_items for select
    to authenticated
    using (exists (
        select 1 from public.inventario_auditorias audit
        where audit.id = audit_id and audit.owner_id = auth.uid()
    ));

drop policy if exists "inventario_auditoria_items_owner_insert" on public.inventario_auditoria_items;
create policy "inventario_auditoria_items_owner_insert"
    on public.inventario_auditoria_items for insert
    to authenticated
    with check (exists (
        select 1 from public.inventario_auditorias audit
        where audit.id = audit_id and audit.owner_id = auth.uid()
    ));

drop policy if exists "inventario_auditoria_items_owner_update" on public.inventario_auditoria_items;
create policy "inventario_auditoria_items_owner_update"
    on public.inventario_auditoria_items for update
    to authenticated
    using (exists (
        select 1 from public.inventario_auditorias audit
        where audit.id = audit_id and audit.owner_id = auth.uid()
    ))
    with check (exists (
        select 1 from public.inventario_auditorias audit
        where audit.id = audit_id and audit.owner_id = auth.uid()
    ));

drop policy if exists "inventario_auditoria_items_owner_delete" on public.inventario_auditoria_items;
create policy "inventario_auditoria_items_owner_delete"
    on public.inventario_auditoria_items for delete
    to authenticated
    using (exists (
        select 1 from public.inventario_auditorias audit
        where audit.id = audit_id and audit.owner_id = auth.uid()
    ));

revoke all on table public.inventario_auditorias from anon;
revoke all on table public.inventario_auditoria_items from anon;
grant select, insert, update, delete on table public.inventario_auditorias to authenticated;
grant select, insert, update, delete on table public.inventario_auditoria_items to authenticated;
grant usage, select on sequence public.inventario_auditoria_items_id_seq to authenticated;

commit;
