#!/usr/bin/env python3
"""
Remove backgrounds for HERENCIA90 preorder images with a local BiRefNet model.

This script intentionally only writes transparent PNG cutouts. The square
catalog assets and review sheets are generated by scripts/preventa-curate-local.mjs.
"""

import argparse
import json
from pathlib import Path

import torch
from PIL import Image, ImageFilter, ImageOps
from torchvision import transforms
from transformers import AutoModelForImageSegmentation


def parse_args():
    parser = argparse.ArgumentParser(description="Remove jersey backgrounds with BiRefNet")
    parser.add_argument("--manifest", required=True, help="JSON file with input/output jobs")
    parser.add_argument("--model", default="ZhengPeng7/BiRefNet", help="Hugging Face model id")
    parser.add_argument("--device", default="auto", choices=["auto", "cpu", "cuda"], help="Inference device")
    parser.add_argument("--size", type=int, default=1024, help="Square inference size")
    parser.add_argument("--mask-blur", type=float, default=0.45, help="Small alpha blur to soften edges")
    parser.add_argument("--trust-remote-code", action="store_true", help="Allow custom model code")
    return parser.parse_args()


def choose_device(value):
    if value == "cuda":
        return "cuda"
    if value == "cpu":
        return "cpu"
    return "cuda" if torch.cuda.is_available() else "cpu"


def load_jobs(manifest_path):
    data = json.loads(Path(manifest_path).read_text(encoding="utf-8"))
    jobs = data.get("jobs", data if isinstance(data, list) else [])
    if not jobs:
        raise ValueError(f"No jobs found in {manifest_path}")
    return jobs


def get_prediction_tensor(output):
    if isinstance(output, dict):
        for key in ("logits", "pred", "prediction", "out", "saliency"):
            if key in output:
                return output[key]
        values = list(output.values())
        return values[-1]
    if isinstance(output, (list, tuple)):
        return output[-1]
    return output


def mask_from_prediction(prediction, original_size):
    if isinstance(prediction, (list, tuple)):
        prediction = prediction[-1]
    if prediction.ndim == 4:
        prediction = prediction[0]
    if prediction.ndim == 3:
        prediction = prediction[0]

    prediction = prediction.detach().float().cpu()
    if prediction.min() < 0 or prediction.max() > 1:
        prediction = prediction.sigmoid()
    else:
        min_val = float(prediction.min())
        max_val = float(prediction.max())
        if max_val > min_val:
            prediction = (prediction - min_val) / (max_val - min_val)

    mask = transforms.ToPILImage()(prediction).convert("L")
    return mask.resize(original_size, Image.Resampling.LANCZOS)


def remove_background(model, image_path, output_path, transform, device, mask_blur):
    image = Image.open(image_path)
    image = ImageOps.exif_transpose(image).convert("RGB")
    original_size = image.size

    tensor = transform(image).unsqueeze(0).to(device)
    with torch.inference_mode():
        prediction = get_prediction_tensor(model(tensor))

    mask = mask_from_prediction(prediction, original_size)
    if mask_blur > 0:
        mask = mask.filter(ImageFilter.GaussianBlur(radius=mask_blur))

    cutout = image.convert("RGBA")
    cutout.putalpha(mask)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    cutout.save(output_path, "PNG", optimize=True)


def main():
    args = parse_args()
    device_name = choose_device(args.device)
    device = torch.device(device_name)

    torch.set_float32_matmul_precision("high")
    model = AutoModelForImageSegmentation.from_pretrained(
        args.model,
        trust_remote_code=args.trust_remote_code,
    )
    model.to(device)
    if device_name == "cpu":
        model.float()
    model.eval()

    transform = transforms.Compose(
        [
            transforms.Resize((args.size, args.size)),
            transforms.ToTensor(),
            transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
        ]
    )

    jobs = load_jobs(args.manifest)
    results = []
    for index, job in enumerate(jobs, start=1):
        input_path = Path(job["input"]).resolve()
        output_path = Path(job["output"]).resolve()
        remove_background(model, input_path, output_path, transform, device, args.mask_blur)
        results.append(
            {
                "slug": job.get("slug"),
                "input": str(input_path),
                "output": str(output_path),
                "status": "ok",
            }
        )
        print(f"[{index}/{len(jobs)}] {job.get('slug') or input_path.name} -> {output_path}")

    print(json.dumps({"model": args.model, "device": device_name, "results": results}, indent=2))


if __name__ == "__main__":
    main()
