CREATE TABLE pedidos (
    id bigint generated by default as identity primary key,
    cliente text not null,
    canal text not null,
    producto_id bigint null, -- Puede ser null si es una referencia eliminada o temporal
    equipo text not null,
    talla text not null,
    cantidad integer not null default 1,
    precio_venta numeric not null,
    costo_usd numeric not null,
    costo_landed_cop numeric not null,
    trm numeric not null,
    estado_pago text not null, -- 'Pendiente', 'Abonado', 'Pagado'
    abono numeric not null default 0,
    estado_entrega text not null, -- 'Pendiente', 'Entregado'
    lote_codigo text not null,
    fecha_pedido date not null,
    fecha_entrega date null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Configurar RLS (Row Level Security) permitiendo acceso anónimo (ya que la app usa RLS abierto para admin interno)
ALTER TABLE pedidos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir todo a anon en pedidos" ON pedidos FOR ALL USING (true) WITH CHECK (true);
